name    'leadps/chocolatey_apps'
version '1.0.2'
source 'UNKNOWN'
author 'Leadership Public Schools'
license 'Apache License, Version 2.0'
summary 'packages that will be installed on window nodes'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
